package vista;

import modelo.Citas;

import javax.swing.*;

/**
 * @author MSI
 */
public class FrmModificarCita extends javax.swing.JFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public Citas citaNueva;

    public FrmModificarCita(Citas citaNueva) {
        initComponents();

        this.citaNueva = citaNueva;
        tfIdNedico.setText(citaNueva.getMedico_id());
        tfIdPaciente.setText(citaNueva.getPaciente_id());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        lblIdMedico = new javax.swing.JLabel();
        lblIdPaciente = new javax.swing.JLabel();
        lblFechaCita = new javax.swing.JLabel();
        tfIdNedico = new javax.swing.JTextField();
        tfIdPaciente = new javax.swing.JTextField();
        btnConfirmarCambios = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        // Agrega el JSpinner para la hora
        SpinnerDateModel sm = new SpinnerDateModel();
        spinnerHora = new JSpinner(sm);
        JSpinner.DateEditor de = new JSpinner.DateEditor(spinnerHora, "HH:mm");
        spinnerHora.setEditor(de);

        setForeground(new java.awt.Color(153, 255, 102));
        setTitle("MODIFICAR CITA\n\n");


        lblIdMedico.setText("ID MEDICO");

        lblIdPaciente.setText("ID PACIENTE");

        lblFechaCita.setText("FECHA CITA");

        tfIdPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        btnConfirmarCambios.setText("Confirmar cambios");
        btnConfirmarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarCambiosActionPerformed(evt);
                citaNueva.setMedico_id(tfIdNedico.getText().trim());
                citaNueva.setPaciente_id(tfIdPaciente.getText().trim());
                citaNueva.setFecha("XX");
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblIdMedico)
                                        .addComponent(lblIdPaciente)
                                        .addComponent(lblFechaCita))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnConfirmarCambios)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(spinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(tfIdNedico, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                                .addComponent(tfIdPaciente)))
                                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblIdMedico)
                                        .addComponent(tfIdNedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblIdPaciente)
                                        .addComponent(tfIdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblFechaCita)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(spinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(btnConfirmarCambios)
                                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>

    private void btnConfirmarCambiosActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Citas c = new Citas();
                new FrmModificarCita(c).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    public javax.swing.JButton btnConfirmarCambios;
    public com.toedter.calendar.JDateChooser jDateChooser1;

    public javax.swing.JTextField tfIdNedico;
    public javax.swing.JTextField tfIdPaciente;
    public javax.swing.JLabel lblFechaCita;
    public javax.swing.JLabel lblIdMedico;
    public javax.swing.JLabel lblIdPaciente;
    public javax.swing.JSpinner spinnerHora;
    // End of variables declaration
}
